### ISSUE TITLE
Specific Wiki problem

### ISSUE THREAD

**Issue by WcDuck** [ChrisNZL/Fauxbar#10]
Not sure if this is worth investigating, but might as well report it.

[This page](http://seesaawiki.jp/w/radioi_34/) has a [search field](https://i.imgur.com/Ig0kWk1.png), now when I try to [search something in Japanese](https://i.imgur.com/9lz8J85.png) since it's a Japanese wiki (here for example 甲鉄城のカバネリ), it [blows up the characters](https://i.imgur.com/0evFV9p.png) completely.

So far this is the only site/search field where this happens to me with this addon though.

**Comment by ChrisNZL** [comment]
Hi, it looks like this is something specific with seesaawiki.jp.

I tried disabling `urlencode` before passing the search query but it made no difference. (fauxbar-1.js, line 421)

Other sites don't seem to have a problem parsing Japanese characters. Not sure what else to try, sorry.
