### ISSUE TITLE
Uncaught TypeError: Failed to execute 'executeSql' on 'SQLTransaction': The callback provided as parameter 3 is not a function.

### ISSUE THREAD

**Issue by fhoshino** [ChrisNZL/Fauxbar#11]
Got a fullpage of errors, for using a day or two, the log grows to 9000+
![2017-02-04_02-05-44](https://cloud.githubusercontent.com/assets/771955/22602518/8251ab20-ea7e-11e6-9ed9-347be858498d.png)

**Comment by fhoshino** [comment]
or, is there a way to disable error log if it seems nothing is broken?

**Comment by ChrisNZL** [comment]
Thanks for posting the error log. An empty array was being passed into the third parameter instead of the function as noted. I've fixed this locally; will publish 1.6.1 soon.

**Comment by ChrisNZL** [comment]
Done.
