### ISSUE TITLE
Option to disable error log if nothing is broken

### ISSUE THREAD

**Issue by fhoshino** [ChrisNZL/Fauxbar#13]
Please add a function which allows the user to disable the log completely if there is simply nothing broken but unknown error which makes the log grow.

**Comment by fhoshino** [comment]
I'm getting a tone load of error logs within 2 days from v62, desperately need an option to disable the logging.
![chrome_2017-11-17_21-00-14](https://user-images.githubusercontent.com/771955/32948541-92a2555e-cbda-11e7-8210-ce19592cca26.png)

**Comment by fhoshino** [comment]
The open error log page just hangs and I can't clear the log.

**Comment by fhoshino** [comment]
![chrome_2017-11-17_21-05-10](https://user-images.githubusercontent.com/771955/32948674-108e1a84-cbdb-11e7-90cb-4e168d2597da.png)

**Comment by ChrisNZL** [comment]
I've created an issue for the error your log mentions: https://github.com/ChrisNZL/Fauxbar/issues/27

**Comment by ChrisNZL** [comment]
Option added now for v1.7.1.

![image](https://user-images.githubusercontent.com/280814/33602810-5c0ef896-da15-11e7-8fb2-68fc793d6f31.png)
