### ISSUE TITLE
Not indexing history

### ISSUE THREAD

**Issue by kr99** [ChrisNZL/Fauxbar#15]
Fauxbar is not indexing my history.  I've tried reinstalling, and rebuilding, and reindexing.  It always says 0 items are indexed from history in the settings pages.

Chrome can see the history items I care about, though.

**Comment by ChrisNZL** [comment]
Any errors in Fauxbar's background page?

To view:
- Go to chrome://extensions/
- Tick the "Developer mode" checkbox
- Under Fauxbar, click "Inspect views: background page"

And, is there anything on Fauxbar's own error log?
chrome-extension://hibkhcnpkakjniplpfblaoikiggkopka/html/fauxbar.errorlog.html
