### ISSUE TITLE
Open all bookmarks in a folder

### ISSUE THREAD

**Issue by fhoshino** [ChrisNZL/Fauxbar#16]
Please add an ability to open all bookmarks in a folder from the menu bar.

**Comment by ChrisNZL** [comment]
Added in v1.7.0.

When browsing your bookmarks, if a folder contains more than 1 bookmark and less than 31 bookmarks, options to open the bookmarks in the current window, new window, or incognito window are now available.

![image](https://cloud.githubusercontent.com/assets/280814/25159040/e75d5dc2-2500-11e7-95e3-cd8db96c745f.png)
