### ISSUE TITLE
Chrome Remote Desktop does not open

### ISSUE THREAD

**Issue by alcosml** [ChrisNZL/Fauxbar#17]
In the Apps section of the New Tab page, clicking on the Chrome Remote Desktop does not open the extension and just blinks the Apps section.

**Comment by ChrisNZL** [comment]
Thanks for spotting this.
Same effect with the Google Play Music app, so it seems it's an issue with non-web apps, eg offline apps I guess that are using special app functionality.

I don't see any errors anywhere so I'm probably not parsing the correct launch params for this type of app for some reason.
"Launch App" isn't an option either if you browse these apps by going Fauxbar > Apps from the fake toolbar.

I'll try to take a look soon.

**Comment by ChrisNZL** [comment]
I'll also note, if you go to `chrome://apps` for now, you can launch your apps from there for the interim.

**Comment by alcosml** [comment]
Yup, that's also my workaround for now :)

Thanks,

Albert Cobacha
SplitmediaLabs, Ltd.

**Comment by ChrisNZL** [comment]
Fixed in v1.7.0. Should come live within an hour.

**Comment by alcosml** [comment]
Confirmed!

Thanks,

Albert Cobacha
SplitmediaLabs, Ltd.
