### ISSUE TITLE
Clicking on Google Shees app directs to blank page

### ISSUE THREAD

**Issue by alcosml** [ChrisNZL/Fauxbar#19]
See: https://321.show/NrnDMt8aX7m

**Comment by ChrisNZL** [comment]
At a glance, is probably an issue with my handling of `chrome-extension://` URLs which this app seems to use for its launch URL.

For the meantime, you can go Right-click > Open App in New Tab, seems to work.

**Comment by ChrisNZL** [comment]
Should be fixed now with v1.7.1.

**Comment by alcosml** [comment]
Verified.

Thanks,

Albert Cobacha
SplitmediaLabs, Ltd.
