### ISSUE TITLE
Not able to close the Fauxbar 'new' tab with mouse gestures

### ISSUE THREAD

**Issue by pvannuff** [ChrisNZL/Fauxbar#2]
I recently installed Fauxbar while I'm also using the crxMouse Chrome Gestures tool. This tool allows you to close the default 'new tab' with a gesture, but this does not work with the Fauxbar one.
I'm guessing because it traps right click itself and does not pass that action along further?

I can easily just use the regular 'new tab' of chrome itself, obviously. But now that I double check it looks like the option in your settings is already turned off, even though it still appears.

The regular chrome settings mention this: An extension, Fauxbar, is controlling this setting.
So I'm not able to turn that 'new tab' behavior back to the regular chrome way, unless I disable Fauxbar entirely. :-(

**Comment by ChrisNZL** [comment]
Hello! I'm not very familiar with crxMouse Chrome Gestures.

Fauxbar's page overrides right-click handling, _however_, if you hold Ctrl while right-clicking, Fauxbar does not override the default right-click context menu.

Not sure if this matters or not, but Fauxbar actually closes the New Tab Page that Chrome creates, and Fauxbar quickly opens its own page to be able to steal focus from Chrome's Omnibox - something Fauxbar can't do if the New Tab page is open. It happens so fast you can't really see the new tab be opened, closed, and then have a new Fauxbar tab be opened in its place (on a fast computer anyway). I don't know if it's relevant or not.

But yeah, I've just installed [CLEAN crxMouse Gestures](https://chrome.google.com/webstore/detail/clean-crxmouse-gestures/mjidkpedjlfnanainpdfnedkdlacidla?hl=en) to try, and it doesn't seem to work on Fauxbar's page.

If you don't need Fauxbar as the New Tab Page, perhaps try giving [Fauxbar Lite](https://chrome.google.com/webstore/detail/fauxbar-lite/bfimmnpbjccjihohjkimphfmmebffbmk) a go.

**Comment by pvannuff** [comment]
Great suggestion for the lite version, I mostly was looking for the added features in the url bar anyway.

I've switched to that version and everything now works peachy. Thanks for the quick reply! :-D
