### ISSUE TITLE
Command+Enter in bar

### ISSUE THREAD

**Issue by RFLaum** [ChrisNZL/Fauxbar#20]
In Mac OS, when using F+Spacebar in the omnibar, using command+enter does not open the page in a new tab, the way it does normally; it just opens the page in the same tab, as if I'd pressed enter alone.

**Comment by ChrisNZL** [comment]
Thanks.
Looks like I could probably edit Fauxbar's `chrome.omnibox.onInputEntered` call to check if the Cmd button is held to determine if the selected URL should be opened in a new tab or not.

**Comment by ChrisNZL** [comment]
Looking into this, I don't think this is possible unfortunately.

With JavaScript, key presses can only be detected with an input event on a page, and Chrome's Omnibox doesn't use any input events. Can't listen for input events on a background page either.
