### ISSUE TITLE
Redirect pages not searchable

### ISSUE THREAD

**Issue by RFLaum** [ChrisNZL/Fauxbar#21]
If I type in a page that's just a redirect, such as slatestarscratchpad.tumblr.com/random , that address is not included in fauxbar results, although it _is_ included in standard omnibox results (and would be included in Firefox's awesomebar results). This is ordinarily not much of a problem because the page it redirects to is the one you want anyway, but in the case of a randomizing redirect such as the one I gave above, it's a bit of a problem.

**Comment by ChrisNZL** [comment]
Hi there,
If you go Fauxbar > Options > Address Box > Results
Uncheck the "Don't show dynamically-generated untitled results" option; this will display redirect pages.
