### ISSUE TITLE
Option to control searchTerms space handling

### ISSUE THREAD

**Issue by fhoshino** [ChrisNZL/Fauxbar#23]
Some legacy search engines do not use + for spaces, they use %20 instead, please add an option to control a specific search engine to use which concat string.

**Comment by ChrisNZL** [comment]
Added to v1.7.1 now.
In the options for the search engines, choose the "Other" encoding to make spaces use `%20`.
![image](https://user-images.githubusercontent.com/280814/33602957-d0aac0fe-da15-11e7-9893-e22c5ce2a8fd.png)
