### ISSUE TITLE
[Feature request] Open in new background tab

### ISSUE THREAD

**Issue by vdun** [ChrisNZL/Fauxbar#24]
Currently: <kbd>CTRL</kbd>+<kbd>ENTER</kbd> -> open in new tab

Expected new option for example:
<kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>ENTER</kbd> -> open in new tab (background)

**Comment by ChrisNZL** [comment]
<kbd>Ctrl</kbd>+<kbd>Enter</kbd> wraps current input with `www.` and `.com` and goes to the address - this is standard behaviour in Chrome and Firefox. I'm not sure why it's opening a new tab for you?

I'm not really in the mood to juggle handling <kbd>Shift</kbd> into the mix, sorry.
