### ISSUE TITLE
Feature request: export/import the index

### ISSUE THREAD

**Issue by lins05** [ChrisNZL/Fauxbar#25]
Fauxbar is great (the No.1 must have on my chrome). But one thing that keeps coming to my mind is: it would be even greater if fauxbar support export the index to a file and support importing it from the file. 

* As a backup mechanism
* Or to setup it on a new machine quickly.

Needless to say this feature would require quite some efforts. So hopefully this can be considered in the developer has bandwidth to work on new features.

**Comment by ChrisNZL** [comment]
Chrome's bookmark system already does this. Bookmark a page and you get:
- Persistent URLs between installs
- Persistent URLs between history clears
- Cross-machine URL syncing

If you want to transfer bookmarks between Google accounts, you can export and import bookmarks via `chrome://bookmarks` > Organize.
