### ISSUE TITLE
could not prepare statement (1 no such column: encoding)

### ISSUE THREAD

**Issue by incoog** [ChrisNZL/Fauxbar#31]
After todays update (1.7.1) I get this error message.

Fauxbar has encountered an error
SQL syntax error: "could not prepare statement (1 no such column: encoding)"
js/fauxbar-1.js, line 1264

Here's the full error log
[Fauxbar_ Error Log.zip](https://github.com/ChrisNZL/Fauxbar/files/1532183/Fauxbar_.Error.Log.zip)

**Comment by ChrisNZL** [comment]
Thanks for reporting this.
I had added an SQL statement to alter the opensearches table with the new encoding column upon Fauxbar launching for the first time with the new version... Worked on my upgrade test, but there must be a race condition or something wrong.

To fix for now, if you go Fauxbar > Options > Management > Rebuild button, it should rebuild the databases fully.

In any case, I will try to push a fix out today to add extra checks to ensure the database has been upgraded, or to force a rebuild if not probably.

**Comment by ChrisNZL** [comment]
I've just pushed v1.7.2, should be available shortly.

I've made it so the alter table statement is executed every time Fauxbar starts (rather than just the once when the extension supposedly updates according to Chrome), so should be fixed.
