### ISSUE TITLE
"Edit Bookmark" does not work

### ISSUE THREAD

**Issue by seanryan-seanryan** [ChrisNZL/Fauxbar#34]
The "Edit Bookmark" option in the new tab's Fauxbar address bar is faulty. It opens Chrome bookmarks, but the bookmark is never shown and the "Search bookmarks" field is blank. I noticed the URL generated by Fauxbar differs from the one Chrome generates when you type in the "Search bookmarks" field.

Chrome  URL: chrome://bookmarks/?q=...webaddress...
Fauxbar URL: chrome://bookmarks/?#q=...webaddress...

When you remove the "#" from "?#q=", then the bookmark search works: "Search bookmarks" field is populated and the bookmark is listed.

Thanks for a brilliant extension!

**Comment by ChrisNZL** [comment]
Thanks. Looks like Chrome changed their bookmarks query param.

**Comment by ChrisNZL** [comment]
Fixed in v1.8.0. Also made the bookmarks tab that opens be selected upon opening.

Will upload to Chrome Web Store soon.
