### ISSUE TITLE
Keyboard shortcut instructions are no longer correct.

### ISSUE THREAD

**Issue by theSloopJohnB** [ChrisNZL/Fauxbar#39]
It looks like Chrome's extension page has changed, and I can no longer use the instructions that Fauxbar provides.

`Open Chrome's Extensions page.
Scroll to the bottom of the page.
Click the "Keyboard shortcuts" link.
Under Fauxbar, several shortcut options will be available.
To modify a shortcut, click an input box, then press your desired keys`

**Comment by ChrisNZL** [comment]
Fixed the link and descriptions in v1.8.0.

Chrome doesn't seem to automatically apply Fauxbar's default shortcuts as specified in the manifest, but the text on Fauxbar's options page suggests what to enter as shortcuts at least.
