### ISSUE TITLE
Feature: Add option 'Highlight matching words'

### ISSUE THREAD

**Issue by vdun** [ChrisNZL/Fauxbar#4]
Add option :
- Highlight matching words
along with:
- Bolden matching words
- Underline matching words

**Comment by ChrisNZL** [comment]
Progress:

![image](https://cloud.githubusercontent.com/assets/280814/21927040/4fa23c8a-d9e9-11e6-8de2-48bbc9294725.png)

Will give the user two `background-color` options for the "normal" results and the "highlighted" results. Looks a little funky for the blue highlighted result but the words are highlighted nonetheless.

**Comment by ChrisNZL** [comment]
Added to 1.6.0.

> Added new option: "Highlight matching words":
> - Available under Options > Address Box > Results.
> - Colors can be changed under Colors & Styling.
