### ISSUE TITLE
Memory usage bug

### ISSUE THREAD

**Issue by Chealer** [ChrisNZL/Fauxbar#40]
According to https://github.com/ChrisNZL/Fauxbar/wiki/FAQ#what-is-fauxbar-memory-helper Fauxbar suffers from a memory usage bug which causes unwarranted RAM usage.

I have no idea if this is still the case, but I have been experiencing serious performance issues with Chrome for some time and Fauxbar is my only extension. This ticket is asking to either solve the bug or discontinue the Memory helper extension.

**Comment by ChrisNZL** [comment]
Back in 2011, memory usage with Fauxbar was an issue; it would increase a fair bit.

7 years later, Chrome's extension memory management has improved (just as a general unscientific observation over the years), and I haven't noticed any extreme memory usage when using Fauxbar these days.

I don't use Fauxbar Memory Helper myself anymore. Might be worth removing it, yeah.

If performance feels like it's suffering, *maybe* try going Fauxbar > Options > Management > Reindex or even Rebuild to recreate its database, though everything's asynchronous in the background as you browse, so not sure it would do much, but wouldn't hurt to try.

**Comment by Chealer** [comment]
Thank you for the advise Chris

**Comment by ChrisNZL** [comment]
Looks like there's a few hundred people using Fauxbar Memory Helper; I'll leave it alone.

**Comment by Chealer** [comment]
Hi @ChrisNZL ,
Should this be considered as a confirmation that Fauxbar Memory Helper remains relevant?

For what it's worth, my performance issues with Chrome haven't been as bad in the last months.

**Comment by ChrisNZL** [comment]
I assume Memory Helper still works.

If it ain't broke, don't fix it  ¯\_(ツ)_/¯

**Comment by Chealer** [comment]
Yes @ChrisNZL but what do you mean by working? Do you just mean it does not break Chrome, or do you mean it _works_ as in it _does something useful_, i.e. it helps with Fauxbar's memory usage?

**Comment by ChrisNZL** [comment]
Fauxbar Memory Helper should do what it says: reloads Fauxbar after a few minutes if your computer is idle and no Fauxbar tabs are open.

At a glance, I noticed Fauxbar was using ~60 MB of RAM. Reloaded Fauxbar, and it then dropped to 20 MB.

If there's no issues of the Memory Helper extension not working, then it works as far as I'm aware.

Whether Chrome is actually tackling extension memory better these days is something that could be profiled, but I don't have the desire to investigate, as it feels like a non-issue.

If you're concerned with memory usage (like if your computer only has 2 GB RAM or something), install Memory Helper. If it's not a concern, don't install it.

**Comment by Chealer** [comment]
Thank you @ChrisNZL 
In that case, why was this ticket closed? You are saying there is a memory usage bug, or are you not?

**Comment by ChrisNZL** [comment]
No, it's not a bug, it's just a factor of an extension that does processing on every page you visit. Memory increases.

Back in 2011/2012, I recall memory being a large issue. Other extension developers (like for ad blockers) reported similar concerns that memory usage was just not being controlled well by Chrome. So I created Memory Helper to try and automatically reduce memory.

Years later, I believe Chrome is better at handling memory for extensions, so I don't bother installing Memory Helper myself anymore. It's still there if desired, but just optional and probably not needed.

>This ticket is asking to either solve the bug or discontinue the Memory helper extension.

So no, memory usage is not a bug, and no, I don't see the need to discontinue Memory Helper for now.
