### ISSUE TITLE
Error when title element is missing

### ISSUE THREAD

**Issue by TimKingtonFC** [ChrisNZL/Fauxbar#42]
When a page is opened that doesn't have a title element, I get this error in the JS console:

updatetitle.js:12 Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at updatetitle.js:12
(anonymous) @ updatetitle.js:12

It's really annoying when "stop on exceptions" is turned on, because I wind up in updatetitle.js instead of the code I'm trying to debug.  It looks like this could be fixed by checking whether target is real before trying to use it.

**Comment by ChrisNZL** [comment]
Fixed in v1.8.0.
