### ISSUE TITLE
Fauxbar Lite's Omnibox search lacks history results

### ISSUE THREAD

**Issue by Chealer** [ChrisNZL/Fauxbar#43]
After switching from Fauxbar to Fauxbar Lite, I noticed that some pages I accessed are missing from the suggested completions in the Omnibox. For example, I accessed URL "https ://github.com/ ChrisNZL/Fauxbar/issues/41", but entering "NZL" in the Omnibox only suggests Google searches.

With another example, this screenshot shows completion for a history entry working:
![works](https://user-images.githubusercontent.com/486141/50987772-93ff8a00-14d8-11e9-841c-bc243ecc9bf0.png)
But with a different "search term" ("7140") also part of the entry's URL, that same entry is not suggested, as can be seen in this screenshot:
![fails](https://user-images.githubusercontent.com/486141/50987773-93ff8a00-14d8-11e9-9a01-ef104603eaf1.png)
Suggestion also fails when there are letters, if trying with "tem7140" for example. It seems completion only works if the search term immediately follows a slash.

**Comment by ChrisNZL** [comment]
To search via Fauxbar (or Fauxbar Lite) from Chrome's Omnibox, you need to type `f ` before your query, like `f item714` or `f 7140`. You'll then see "Fauxbar" or "Fauxbar Lite" at the start of the Omnibox UI.

![image](https://user-images.githubusercontent.com/280814/50989903-80563100-1575-11e9-8206-cac2cb6def71.png)

**Comment by Chealer** [comment]
Thank you Chris.
Sorry for this bogus report in that case. Could this be considered instead as a request to replace "press F+Spacebar" with «type "f " (the letter "f" followed by a space)» in Fauxbar Lite's presentation? I ignored that part because I couldn't understand it, thinking this was asking to press 2 keys simultaneously.

**Comment by ChrisNZL** [comment]
For v1.8.0, I've added CSS key styling for <kbd>F</kbd>+<kbd>Spacebar</kbd> in the options to make it clearer.

Also added keyboard tags in the wiki articles just now.
