### ISSUE TITLE
Feature: Trim Text before search

### ISSUE THREAD

**Issue by cpmcgrath** [ChrisNZL/Fauxbar#44]
When you double click on a word in (most of) Windows, it also selects the space after it (And if you then copy, it's included in the copied text). Most of the time this is harmless, however there's one item I've added to my search engine where this causes the search to fail (It's not really a search, just creates a url to a particular ticket in the system)

I notice that when you paste in the chrome location bar, it immediately performs a trim on the text to be pasted. I feel this is the ideal behaviour. It would be great if it could be implemented in Fauxbar

**Comment by ChrisNZL** [comment]
Adding options in v1.8.0, both enabled by default, will be under Options > General > Input Boxes:
- Trim pasted text, and
- Trim search queries
