### ISSUE TITLE
Fail to fetch bookmarks in brave 1.2.41

### ISSUE THREAD

**Issue by fhoshino** [ChrisNZL/Fauxbar#55]
![brave_2020-01-07_20-36-47](https://user-images.githubusercontent.com/771955/71896028-93eaa680-318d-11ea-9c36-69d2d8023928.png)

**Comment by fhoshino** [comment]
Reference:
https://github.com/brave/brave-browser/issues/5158

**Comment by ChrisNZL** [comment]
I'm not interested in tackling other browsers' issues, sorry. There are too many forks out there.

Chrome and Chromium are what Fauxbar is aimed at complementing.
