### ISSUE TITLE
Feature: Fuzzy search

### ISSUE THREAD

**Issue by vdun** [ChrisNZL/Fauxbar#6]
Example. Typing: `tg`
would match (words having the letters 't' and 'g'):
`caT bloG`
`kiTty Globe`
`planeT Ground`

maybe using https://github.com/krisk/Fuse ?

**Comment by ChrisNZL** [comment]
Any clarifications on this? Can you give examples of what you'd like to type and expect to get returned?

**Comment by vdun** [comment]
I edited the description. is it clear ?

**Comment by ChrisNZL** [comment]
This behaviour can be achieved by adding a space between each letter.
So if you searched for `t g` you would get all three results in your example.

**Comment by vdun** [comment]
Hidden trick. thx
