### ISSUE TITLE
Make Search/Open-url the default action of Fauxbar's Address box - add as config option

### ISSUE THREAD

**Issue by michkot** [ChrisNZL/Fauxbar#60]
Hi! I recently switched from Opera's (i.e. chromium) flavor of omnibox to Fauxbar. I am very happy with usability of the searches in bookmarks and history. However, since I often switch computers and browsers, I am impaired by my generic muscle memory of "press open new tab shortcut, write w/e I want to google-search and press enter" when using Fauxbar - Fauxbar defaults to select  w/e if finds in history/bookmarks that matches the query (if it finds something), and I have to press "up" to select the address bar to "switch" to search/try-open-as-url behavior. 

What I desire is one more configuration option, that would make the selection "stick" to the address bar, so that default action is "search/open-url" and I have to press "down" to select any of the query results.

P.S.: I understand that the project is in "mature & not developed" state, hover I hope such a change would be simple & beneficial  enough so that I do not have to fork&try-it myself :)

**Comment by ChrisNZL** [comment]
Fauxbar's Address Box (eg search your history or bookmarks) and Search Box (use a search engine) are very separated when it comes to displaying results. There's no mixing of the two at the moment.

You can press <kbd>Tab</kbd> to change focus between the input boxes.

To use a search engine from the Address Box, for example Google, type <kbd>g</kbd> then <kbd>Spacebar</kbd>, or click the little ▼ triangle icon to reveal a menu.

Fauxbar mimics classic Firefox's behaviour from ~2011... Firefox did not have a multi-mix of different results at the time, and thus I did not try to model it as much.

Only in recent years has there been a large shift for letting one input box suggest multiple different actions.

I can see such an option being useful, so this issue and suggestion sounds good. But I would not expect a quick fix or implementation from me in the near future. Fork away and/or do a merge pull request if you fancy.

---

Related option that might be useful (though not a full solution): 
- Options > General > Input Boxes > Display: <kbd>Search Box then Address Box</kbd>

**Comment by michkot** [comment]
I have cloned the repo and readied myself for work on the PR, when I realized the feature is already implemented, but I did not see it! 

By fault, **Auto assist** is set to **_auto-highlight_** the first result. Switching it to **_auto-fill URL_** mimics typical behavior of nowadays browsers (with search suggestions off). Alternatively, **_don't assist me_** also works. Thanks again!
![image](https://user-images.githubusercontent.com/14879243/107121174-4f01d980-6891-11eb-80dc-e5a961b9eb80.png)
