### ISSUE TITLE
Tile thumbnails not updating

### ISSUE THREAD

**Issue by fadster** [ChrisNZL/Fauxbar#61]
I disabled and re-enabled the extension. The tile thumnails are gone and no longer updating.

**Comment by fadster** [comment]
Seems they only refresh when clicked on, not if the page they point to is opened separately. Some tiles needed several tries to refresh.

**Comment by ChrisNZL** [comment]
If my memory serves me right, common causes for tile thumbnails not updating:

- URL of the tile is not the final URL anymore; can occur if the page ends up redirecting or changing its URL in any way.

- Page has to finish "loading" (eg the loading indicator in the page's tab has to stop); the thumbnail then updates ~2 seconds later if the page is the current tab).

- Page has to not be scrolled at all; scrollbar has to be at the top.

**Comment by fadster** [comment]
@ChrisNZL Thanks for the info!
